# Generated by Django 4.2.9 on 2026-02-23 18:56

from django.conf import settings
import django.contrib.auth.models
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("fr", "Français"), ("en", "English")],
                        default="fr",
                        max_length=2,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="core_user_set",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="core_user_permissions_set",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "db_table": "users",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("commune", "Commune"), ("quartier", "Quartier")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                (
                    "bounds",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("population", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_locations",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lieu",
                "verbose_name_plural": "Lieux",
                "db_table": "locations",
                "ordering": ["type", "name"],
            },
        ),
        migrations.CreateModel(
            name="TransportMode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bus", "Bus"),
                            ("taxi", "Taxi"),
                            ("train", "Train"),
                            ("metro", "Métro"),
                            ("gbaka", "Gbaka"),
                            ("woro", "Woro-Woro"),
                            ("car_rental", "Location de voiture"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Emoji ou classe d'icône", max_length=10
                    ),
                ),
                ("color", models.CharField(help_text="Code couleur hex", max_length=7)),
                ("description", models.TextField(blank=True)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix de base en FCFA",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price_per_km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix par kilomètre en FCFA",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "average_speed",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Vitesse moyenne en km/h",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "comfort_rating",
                    models.IntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "security_rating",
                    models.IntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("operating_hours_start", models.TimeField(blank=True, null=True)),
                ("operating_hours_end", models.TimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Mode de transport",
                "verbose_name_plural": "Modes de transport",
                "db_table": "transport_modes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_criteria",
                    models.CharField(
                        choices=[
                            ("fastest", "Plus rapide"),
                            ("cheapest", "Moins cher"),
                            ("balanced", "Équilibré"),
                            ("safest", "Plus sécurisé"),
                        ],
                        default="balanced",
                        max_length=20,
                    ),
                ),
                (
                    "max_walking_distance",
                    models.IntegerField(
                        default=500,
                        help_text="Distance maximale de marche en mètres",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("accessibility_needs", models.BooleanField(default=False)),
                (
                    "budget_preference",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyen"),
                            ("high", "Élevé"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "comfort_preference",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyen"),
                            ("high", "Élevé"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "security_preference",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyen"),
                            ("high", "Élevé"),
                        ],
                        default="high",
                        max_length=10,
                    ),
                ),
                ("notifications_enabled", models.BooleanField(default=True)),
                (
                    "avoid_transport_modes",
                    models.ManyToManyField(
                        blank=True, related_name="avoided_by", to="core.transportmode"
                    ),
                ),
                (
                    "preferred_transport_modes",
                    models.ManyToManyField(
                        blank=True, related_name="preferred_by", to="core.transportmode"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence utilisateur",
                "verbose_name_plural": "Préférences utilisateurs",
                "db_table": "user_preferences",
            },
        ),
        migrations.CreateModel(
            name="TransportStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "stop_type",
                    models.CharField(
                        choices=[
                            ("bus_stop", "Arrêt de bus"),
                            ("train_station", "Gare"),
                            ("metro_station", "Station de métro"),
                            ("taxi_stand", "Station de taxi"),
                            ("terminal", "Terminal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Équipements: {shelter: true, bench: true, etc.}",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_stops",
                        to="core.location",
                    ),
                ),
                (
                    "transport_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="core.transportmode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arrêt de transport",
                "verbose_name_plural": "Arrêts de transport",
                "db_table": "transport_stops",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TransportRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Ex: Ligne 81", max_length=200)),
                ("code", models.CharField(help_text="Ex: L81", max_length=20)),
                (
                    "route_path",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "estimated_duration_minutes",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "frequency_minutes",
                    models.IntegerField(
                        help_text="Fréquence de passage en minutes",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "destination_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes_to",
                        to="core.transportstop",
                    ),
                ),
                (
                    "origin_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes_from",
                        to="core.transportstop",
                    ),
                ),
                (
                    "transport_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="core.transportmode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de transport",
                "verbose_name_plural": "Lignes de transport",
                "db_table": "transport_routes",
                "ordering": ["transport_mode", "code"],
            },
        ),
        migrations.CreateModel(
            name="TrafficData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                (
                    "traffic_level",
                    models.CharField(
                        choices=[
                            ("low", "Fluide"),
                            ("moderate", "Modéré"),
                            ("high", "Dense"),
                            ("very_high", "Très dense"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "average_speed_kmh",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "day_of_week",
                    models.IntegerField(
                        help_text="0=Lundi, 6=Dimanche",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "hour_of_day",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ]
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traffic_data",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donnée de trafic",
                "verbose_name_plural": "Données de trafic",
                "db_table": "traffic_data",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "origin_coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "destination_coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "search_criteria",
                    models.CharField(
                        choices=[
                            ("fastest", "Plus rapide"),
                            ("cheapest", "Moins cher"),
                            ("balanced", "Équilibré"),
                            ("safest", "Plus sécurisé"),
                        ],
                        default="balanced",
                        max_length=20,
                    ),
                ),
                ("search_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="searches_to",
                        to="core.location",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="searches_from",
                        to="core.location",
                    ),
                ),
                (
                    "selected_transport_mode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.transportmode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recherche",
                "verbose_name_plural": "Historique des recherches",
                "db_table": "search_history",
                "ordering": ["-search_date"],
            },
        ),
        migrations.CreateModel(
            name="RouteSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "segment_order",
                    models.IntegerField(help_text="Ordre dans l'itinéraire"),
                ),
                (
                    "segment_path",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "from_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments_from",
                        to="core.transportstop",
                    ),
                ),
                (
                    "to_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments_to",
                        to="core.transportstop",
                    ),
                ),
                (
                    "transport_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="core.transportroute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Segment d'itinéraire",
                "verbose_name_plural": "Segments d'itinéraire",
                "db_table": "route_segments",
                "ordering": ["transport_route", "segment_order"],
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("address", models.TextField()),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="CI"
                    ),
                ),
                (
                    "cuisine_type",
                    models.JSONField(
                        default=list,
                        help_text="Types de cuisine: ['ivoirienne', 'française', etc.]",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("rating_count", models.IntegerField(default=0)),
                (
                    "price_range",
                    models.CharField(
                        choices=[
                            ("cheap", "Économique"),
                            ("moderate", "Modéré"),
                            ("expensive", "Cher"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "opening_hours",
                    models.JSONField(
                        default=dict, help_text="Horaires d'ouverture par jour"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("photos", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurants",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Restaurant",
                "verbose_name_plural": "Restaurants",
                "db_table": "restaurants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.UUIDField()),
                (
                    "rating_type",
                    models.CharField(
                        choices=[
                            ("transport", "Transport"),
                            ("hotel", "Hôtel"),
                            ("restaurant", "Restaurant"),
                            ("car_rental", "Location de voiture"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "comfort_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "security_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "cleanliness_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "punctuality_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation",
                "verbose_name_plural": "Évaluations",
                "db_table": "ratings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "source",
                    models.CharField(
                        help_text="Source de l'information (API, user_reported, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices_to",
                        to="core.location",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices_from",
                        to="core.location",
                    ),
                ),
                (
                    "transport_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="core.transportmode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de prix",
                "verbose_name_plural": "Historique des prix",
                "db_table": "price_history",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("address", models.TextField()),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="CI"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "star_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("rating_count", models.IntegerField(default=0)),
                (
                    "price_range",
                    models.CharField(
                        choices=[
                            ("budget", "Budget"),
                            ("moderate", "Modéré"),
                            ("luxury", "Luxe"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "min_price_fcfa",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "max_price_fcfa",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "amenities",
                    models.JSONField(
                        default=dict,
                        help_text="Équipements: {wifi: true, pool: true, restaurant: true, etc.}",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "photos",
                    models.JSONField(
                        blank=True, default=list, help_text="URLs des photos"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotels",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hôtel",
                "verbose_name_plural": "Hôtels",
                "db_table": "hotels",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CarRental",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("address", models.TextField()),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="CI"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("rating_count", models.IntegerField(default=0)),
                (
                    "price_per_day_fcfa",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "car_types_available",
                    models.JSONField(
                        default=list,
                        help_text="Types de voitures: ['sedan', 'suv', '4x4', etc.]",
                    ),
                ),
                (
                    "amenities",
                    models.JSONField(
                        default=dict,
                        help_text="Équipements: {gps: true, ac: true, etc.}",
                    ),
                ),
                ("insurance_included", models.BooleanField(default=False)),
                ("unlimited_mileage", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("photos", models.JSONField(blank=True, default=list)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_rentals",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agence de location",
                "verbose_name_plural": "Agences de location",
                "db_table": "car_rentals",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="transportstop",
            index=models.Index(
                fields=["transport_mode", "location"],
                name="transport_s_transpo_3fe982_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transportroute",
            index=models.Index(
                fields=["transport_mode", "is_active"],
                name="transport_r_transpo_e030f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trafficdata",
            index=models.Index(
                fields=["day_of_week", "hour_of_day"],
                name="traffic_dat_day_of__22b3d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trafficdata",
            index=models.Index(
                fields=["location", "recorded_at"],
                name="traffic_dat_locatio_290b49_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["user", "search_date"], name="search_hist_user_id_8838cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["origin", "destination"], name="search_hist_origin__22ee3e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="routesegment",
            unique_together={("transport_route", "segment_order")},
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["location", "is_active"], name="restaurants_locatio_aded90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["content_type", "object_id"], name="ratings_content_829faf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["user", "created_at"], name="ratings_user_id_7f9f81_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("user", "content_type", "object_id")},
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["transport_mode", "origin", "destination"],
                name="price_histo_transpo_384bca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["recorded_at"], name="price_histo_recorde_9f304b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["name", "type"], name="locations_name_ff19b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hotel",
            index=models.Index(
                fields=["location", "is_active"], name="hotels_locatio_f48bb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hotel",
            index=models.Index(
                fields=["price_range"], name="hotels_price_r_38b372_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carrental",
            index=models.Index(
                fields=["location", "is_active"], name="car_rentals_locatio_bb84c4_idx"
            ),
        ),
    ]
