# Generated by Django 4.2.9 on 2026-02-23 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_carrental_updated_at_alter_hotel_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.location",
            ),
        ),
    ]
