# Generated by Django 4.2.9 on 2026-02-23 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_hotel_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="location",
            field=models.ForeignKey(
                default="076c6f71-7201-48c9-9fe0-b78590bcbe22",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotels",
                to="core.location",
            ),
        ),
    ]
