# Generated by Django 4.2.9 on 2026-02-23 21:14

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_hotel_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="location",
            field=models.ForeignKey(
                default=core.models.Hotel.get_default_location,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotels",
                to="core.location",
            ),
        ),
    ]
